export const astar = async () => (await import('astar')).default;
export const wireframe = async () => (await import('wireframe')).default;
export const videoascii = async () => (await import('videoascii')).default;
export const boltzmann = async () => (await import('boltzmann')).default;
export const vu = async () => (await import('vu')).default;
export const conway = async () => (await import('conway')).default;
export const projectwavybits = async () => (await import('projectwavybits')).default;
export const initLispish = async () => (await import('./lispish')).default;
export const initLidrisp = async () => (await import('./lidrisp')).default;