name:                site
version:             0.1.0.0
github:              "ebenpack/ebenpack.github.io"
license:             MIT
author:              "ebenpack"
maintainer:          "example@example.com"
copyright:           "2020 ebenpack"

extra-source-files:
- README.MD

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/testfoo#readme>

dependencies:
- base >= 4.7 && < 5

executables:
  site:
    main: site.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hakyll
    - filepath
    - pandoc
    - containers
    - time
